version: '3.8'

services:

  postgres-db:
    image: 'postgres:15-alpine' # Imagen más reciente y ligera
    container_name: postgres_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - express_net # Renombrado para consistencia

  express:
    build: .
    image: express-api-image
    container_name: express
    restart: always
    ports:
      - 3000:3000 
    volumens:
      -.:/usr/src/app
      -/usr/src/app/node_modules
    networks:
      - express_net # Renombrado para consistencia
    depends_on:
     - postgres-db

# Definición de volúmenes y redes
volumes:
  postgres_data:

networks:
  express_net:
    driver: bridge
